### ISSUE TITLE
Template (answer key csv) selection 

### ISSUE THREAD

**Issue by Park-Patrick** [Park-Patrick/fidvalidator#15]
- Could be from drop down menu
- Correct CSVs stored on repo with references to path

**Comment by kaitj** [comment]
Templates to use: 
* Agile12v2016 (?)
* Colin27
* MNI2009cAsym

One suggestion, @ostanley suggested this as a module linking with afids so that templates are called by association. (Ostanley can clarify this more)

@jclauneuro Were there other templates we would want to include for comparisons and is Agile12 one of the templates that we want to use?

**Comment by jclauneuro** [comment]
Thanks for looping me in! Looks like a good set of templates to start with. We have a few more that have been validated including PD25, BigBrainSym, MNI2009bSym that could be included at some point?

**Comment by ostanley** [comment]
@jclauneuro we can make it a submodule which just links the fidvalidator repo and the afids repo so that when you update one it is just one command to sync it to the other. Is that something you are interested in? the sync would just be a git pull which we could eventually include in CI.

**Comment by jclauneuro** [comment]
Definitely interesting, @ostanley. Sounds like a great way to scale up to include any number of templates/individual participant scans at some point.

**Comment by ostanley** [comment]
I'll add the submodule in soon with some instructions about how to update it. We can always change it if we decide we just want hardcoded things.

**Comment by Park-Patrick** [comment]
implemented dropdown menu in PR #20 . Just need to link templates from whichever directory / repo we choose

**Comment by ostanley** [comment]
Closing this issue after submodule integration.
