### ISSUE TITLE
Fiducial Names

### ISSUE THREAD

**Issue by kaitj** [Park-Patrick/fidvalidator#25]
Mentioned in a previous PR.

Some fiducials names from template in sub-module are mismatched with protocol (@jclauneuro)

Fiducials affected:
- culmen -> Culmen
- intermammillary sulcus -> Intermammillary sulcus
- genu of CC -> Genu of CC 
- splenium -> Splenium of CC

Templates affected:
- sub-Agile12v2016
- sub-Colin27
- sub-MNI2009cAsym
- sub-PD25

**Comment by kaitj** [comment]
@tkkuehn will need to fix test cases once fiducial names are fixed

**Comment by kaitj** [comment]
Make the comparisons case insensitive as capitalisation is not important at this stage

**Comment by tkkuehn** [comment]
Just to make sure the discussion here addresses all the initial questions, the answer, at least for now, is that capitalization shouldn't matter and the splenium should have `desc` "Splenium of CC", so the templates need to be updated (which Jon has done in `afids-examples`).
