### ISSUE TITLE
Update README / Add instructions

### ISSUE THREAD

**Issue by kaitj** [Park-Patrick/fidvalidator#41]
An update should be / needs to be made with the new instructions with the (future) migration to heroku. There are screenshots on the mattermost with detailed steps, just needs to be added.

**Comment by Park-Patrick** [comment]
agreed

![Image from iOS(2)](https://user-images.githubusercontent.com/12662110/68960928-2af33d80-079f-11ea-9d0b-0f3b588a5dad.jpg)
![Image from iOS(1)](https://user-images.githubusercontent.com/12662110/68960929-2b8bd400-079f-11ea-872a-58d74c8a85ec.jpg)
![Image from iOS](https://user-images.githubusercontent.com/12662110/68960930-2b8bd400-079f-11ea-9edc-c2d6bbcd0fbe.jpg)

**Comment by kaitj** [comment]
See #44

**Comment by kaitj** [comment]
Merged with #44
